server:
  port: 8184

customer-service:
  customer-topic-name: customer


spring:
  jpa:
    open-in-view: false
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: eunju
    password: qwer1234!
    driver-class-name: org.postgresql.Driver
    platform: postgres
    data: classpath:init-data.sql
    schema: classpath:init-schema.sql
    initialization-mode: always

logging:
  level:
    root: INFO  # 기본 로그 레벨
    org.springframework: TRACE  # 스프링 프레임워크 관련 디버그 로그
#    org.hibernate: DEBUG  # Hibernate 관련 디버그 로그
#    com.zaxxer.hikari: DEBUG  # HikariCP 연결 풀 관련 디버그 로그
#    your.package.name: DEBUG  # 당신의 패키지 관련 디버그 로그 (예: com.example)